package view;

import models.Usuarios;

public class JFMenu extends javax.swing.JFrame {

    Usuarios user;

    /**
     * Creates new form JFMenu
     */
    public JFMenu(Usuarios user) {
        initComponents();
        this.user = user;
        if(user.getCodigoPerfil().getCodigo() ==2){
            JBAutores.setVisible(false);
            JBCajones.setVisible(false);
            JBClasificacion.setVisible(false);
            JBEstantes.setVisible(false);
            JBLibro.setVisible(false);
            JBPaises.setVisible(false);
            JBProveedores.setVisible(false);
            JBSucursal.setVisible(false);
            JBTemas.setVisible(false);
            JBTipos.setVisible(false);
            JBUsuario.setVisible(false);
        }else if (user.getCodigoPerfil().getCodigo() == 3) {
            JBAutores.setVisible(false);
            JBCajones.setVisible(false);
            JBClasificacion.setVisible(false);
            JBEstantes.setVisible(false);
            JBLibro.setVisible(false);
        }
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JBAutores = new javax.swing.JButton();
        JBCajones = new javax.swing.JButton();
        JBClasificacion = new javax.swing.JButton();
        JBEstantes = new javax.swing.JButton();
        JBPaises = new javax.swing.JButton();
        JBProveedores = new javax.swing.JButton();
        JBSucursal = new javax.swing.JButton();
        JBTemas = new javax.swing.JButton();
        JBTipos = new javax.swing.JButton();
        JBUsuario = new javax.swing.JButton();
        JBBuscar = new javax.swing.JButton();
        JBLibro = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JBAutores.setText("Autores");

        JBCajones.setText("Cajones");
        JBCajones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JBCajonesMouseClicked(evt);
            }
        });

        JBClasificacion.setText("Clasificacion");

        JBEstantes.setText("Estantes");

        JBPaises.setText("Paises");

        JBProveedores.setText("Proveedores");
        JBProveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBProveedoresActionPerformed(evt);
            }
        });

        JBSucursal.setText("Sucursales");
        JBSucursal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBSucursalActionPerformed(evt);
            }
        });

        JBTemas.setText("Temas");

        JBTipos.setText("Tipos");

        JBUsuario.setText("Usuario");

        JBBuscar.setText("Buscar");

        JBLibro.setText("Libro");

        jLabel1.setText("Biblioteca UDB");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JBAutores, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(JBEstantes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(JBSucursal, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(JBUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(JBLibro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(JBCajones, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                            .addComponent(JBPaises, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(JBTemas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(74, 74, 74)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JBBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JBTipos, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(JBClasificacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(JBProveedores, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JBAutores)
                    .addComponent(JBCajones)
                    .addComponent(JBClasificacion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JBEstantes)
                    .addComponent(JBPaises)
                    .addComponent(JBProveedores))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JBSucursal)
                    .addComponent(JBTipos)
                    .addComponent(JBTemas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JBUsuario)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(JBLibro)
                        .addComponent(JBBuscar)))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JBSucursalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBSucursalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JBSucursalActionPerformed

    private void JBProveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBProveedoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JBProveedoresActionPerformed

    private void JBCajonesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JBCajonesMouseClicked
        JFCajones fCajones = new  JFCajones();
        fCajones.setVisible(true);
    }//GEN-LAST:event_JBCajonesMouseClicked



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBAutores;
    private javax.swing.JButton JBBuscar;
    private javax.swing.JButton JBCajones;
    private javax.swing.JButton JBClasificacion;
    private javax.swing.JButton JBEstantes;
    private javax.swing.JButton JBLibro;
    private javax.swing.JButton JBPaises;
    private javax.swing.JButton JBProveedores;
    private javax.swing.JButton JBSucursal;
    private javax.swing.JButton JBTemas;
    private javax.swing.JButton JBTipos;
    private javax.swing.JButton JBUsuario;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
